name: smart-home
base: core18
version: '0.2'  # Just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

  #grade: stable # must be 'stable' to release into candidate/stable channels
  #confinement: strict # use 'strict' once you have the right plugs and slots

grade: devel  # Must be 'stable' to release into candidate/stable channels
confinement: devmode
#architectures: [all]

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  smart-home:
    after: [alsa-mixin]
    plugin: dump
    source: .
    override-build: |
      git clone https://github.com/friendlyarm/WiringNP
      cd WiringNP/
      chmod 755 build
      ./build
      cd ..

      scripts/bashScripts/dartSdkDownload.sh  # Downloading dart-sdk for the correct architecture


      cd scripts/bashScripts/
      ./compileAllCFiles.sh # Have to be executed when working directory is this file location
      cd ../..


      unzip dartsdk-*.zip
      rm dartsdk-*.zip
      cd SmartDeviceDart
      ../dart-sdk/bin/pub get --no-precompile
      cd ..
      chmod -R +rx dart-sdk/
      dart-sdk/bin/dart2aot SmartDeviceDart/bin/main.dart main.aot

      rm -r SmartDeviceDart

      #pip3 install --upgrade pip
      #
      #pip3 install wheel
      #pip3 install --upgrade pip
      #
      #pip3 install pyaudio

      #wget http://downloads.sourceforge.net/swig/swig-3.0.10.tar.gz
      #tar -xvzf swig-3.0.10.tar.gz
      #cd swig-3.0.10
      #sudo ./configure --prefix=/usr                  \
      #--without-clisp                    \
      #--without-maximum-compile-warnings &&
      #sudo make
      #sudo make install &&
      #sudo install -v -m755 -d /usr/share/doc/swig-3.0.10 &&
      #sudo cp -v -R Doc/* /usr/share/doc/swig-3.0.10

      snapcraftctl build

    build-packages:
      - wget
      - unzip
      - git
      - gcc
      - make
      - python3-pip
      - libevent-dev
      - libperl-dev
      - libatlas-base-dev
      - libasound2-plugins
      - libasound-dev
    stage-packages:
      - libatlas-base-dev
      - libevent-dev

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  smart-home:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: dart-sdk/bin/dartaotruntime $SNAP/main.aot $SNAP
    daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe, audio-playback, audio-record, pulseaudio, alsa]
