name: smart-home  # You prowow man thats prity collbably want to 'snapcraft register <name>'
base: core18  # The base snap is the execution environment for this snap
version: '0.2'  # Just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

  #grade: stable # must be 'stable' to release into candidate/stable channels
  #confinement: strict # use 'strict' once you have the right plugs and slots

grade: devel  # Must be 'stable' to release into candidate/stable channels
confinement: devmode
#architectures: [all]

parts:
  smart-home :
    plugin: dump
    source: .
    override-build: |
      bashScripts/dartSdkDownload.sh  # Downloading dart-sdk for the correct architecture 
      
      unzip dartsdk-*.zip
      rm dartsdk-*.zip
      cd SmartDeviceDart
      ../dart-sdk/bin/pub get --no-precompile
      cd ..
      dart-sdk/bin/dart2aot SmartDeviceDart/bin/main.dart main.aot
      
      rm -r SmartDeviceDart

      git clone https://github.com/friendlyarm/WiringNP
      cd WiringNP/
      chmod 755 build
      ./build
      
      cd ..
      cd cScripts/

      gcc -Wall -o turnOff turnOff.c -lwiringPi -lpthread
      rm turnOff.c

      gcc -Wall -o turnOn turnOn.c -lwiringPi -lpthread
      rm turnOn.c

      gcc -Wall -o buttonPress buttonPress.c -lwiringPi -lpthread
      rm buttonPress.c

      cd ..

      snapcraftctl build
  
    build-packages:
      - wget
      - unzip
      - git
      - gcc
      - make

apps:
  smart-home :
    command: dart-sdk/bin/dartaotruntime $SNAP/main.aot $SNAP    
    daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe]
