name: smart-home
base: core18
version: '0.3'  # Just for humans, typically '1.2+git' or '1.3.2'
summary: The best app that I made.
description: |
  The best app smart home snap.

grade: devel  # stable
confinement: devmode  # use 'strict' once you have the right plugs and slot
#architectures: [all]

parts:
  #  alsa-mixin: # Not working inside snap with root privileges
  #    plugin: dump
  #    source: https://github.com/diddlesnaps/snapcraft-alsa.git
  #    source-subdir: snapcraft-assets
  #    build-packages:
  #      - libasound2-dev
  #    stage-packages:
  #      - libasound2
  #      - libasound2-plugins

  smart-home:
    #    after: [alsa-mixin]
    plugin: dump
    source: .
    override-build: |
      git clone https://github.com/guyluz11/WiringNP.git
      # git clone https://github.com/friendlyarm/WiringNP  // Does not work on the armbian os,  https://forum.armbian.com/topic/13889-nanopiduo2-wiringnp-unable-to-determine-board-revision/
      cd WiringNP/
      chmod 755 build
      ./build
      cd ..

      sudo scripts/bashScripts/nativeExecutableMaker.sh  # Downloading dart-sdk for the correct architecture.


      cd scripts/bashScripts/
      ./compileAllCFiles.sh # Have to be executed when working directory is this file location
      cd ../..

      rm -r SmartDeviceDart

      snapcraftctl build

    build-packages:
      - wget
      - unzip
      - git
      - gcc
      - make
      - libatlas-base-dev
      - libasound-dev
      # - apt-get install g++ or avr-libc # stdint.h: No such file or directory
    stage-packages:
      - libatlas-base-dev
      - libevent-dev

#layout: # Taneling the alsa comands inside the snap to the alsa on the device
#  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
#    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  smart-home:
    #    command-chain: ["snap/command-chain/alsa-launch"]
    command: main.exe $SNAP
    daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe, audio-playback, audio-record, pulseaudio, alsa]
