name: smart-home # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

  #grade: stable # must be 'stable' to release into candidate/stable channels
  #confinement: strict # use 'strict' once you have the right plugs and slots


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode
#confinement: classic
architectures: [all]
#architectures: [arm]
#architectures:
#  - build-on: armhf
#    run-on: armhf
parts:
  setup:
    plugin: python
    python-version: python3
    override-build: |
      git clone https://github.com/chainsx/RPi.GPIO.NP.git
      cd RPi.GPIO.NP
      sudo python3 setup.py install
      python3 setup.py install
      cd
      snapcraftctl build

    source: .
    #python-packages: [NPi.GPIO]
    build-packages:
      - git
      - python3
    stage-packages:
      - python3

  smart-home :
    plugin: dump
    source: .
    override-build: |
      wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.4.1/sdk/dartsdk-linux-arm64-release.zip  # For arm64
      
      # wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.4.1/sdk/dartsdk-linux-arm-release.zip  # For arm
      # wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.4.1/sdk/dartsdk-linux-x64-release.zip    # For linux intel 64
      # sdk url: https://dart.dev/tools/sdk/archive
      unzip dartsdk-*.zip
      rm dartsdk-*.zip
      cd SmartDeviceDart
      ../dart-sdk/bin/pub get --no-precompile
      cd ..
      dart-sdk/bin/dart2aot SmartDeviceDart/bin/main.dart main.aot
      
      # rm -r SmartDeviceDart
      snapcraftctl build
  
    build-packages:
      - wget
      - unzip

apps:
  smart-home :
    # command: dart-sdk/bin/dart $SNAP/SmartDeviceDart/bin/main.dart NanoPi_Duo2 # For dart file, $SNAP is the variable of location of the snap
    # command: dart-sdk/bin/dartaotruntime $SNAP/main.aot NanoPi_Duo2 # For .aot file
    command: dart-sdk/bin/dartaotruntime $SNAP/main.aot NanoPi_Duo2     # For nanoPiDuo2 file, Can also be nanoPiNeo, nanoPiNeo2
    
    daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe]
