name: smart-home # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

  #grade: stable # must be 'stable' to release into candidate/stable channels
  #confinement: strict # use 'strict' once you have the right plugs and slots


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode
#confinement: classic
architectures: [all]

parts:
  smart-home :
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
           
  
      wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.3.1/sdk/dartsdk-linux-arm64-release.zip
      rm -r dart-sdk
      unzip dartsdk-*
      rm dartsdk-*.zip
    #stage-packages:
      #- make
      #- g++
    build-packages:
      - wget
      - unzip

apps:
  smart-home :
    command: dart-sdk/bin/dart $SNAP/SmartDeviceDart/bin/main.dart
    #command: dart-sdk/bin/dartaotruntime $SNAP/main.dart.aot
